n1 = input("digite o 1º numero: ")
n2 = input("digite o 2º numero: ")
n3 = input("digite o 3º numero: ") 
n4 = input("digite o 4º numero: ") 
n5 = input("digite o 5º numero: ") 
n6 = input("digite o 6º numero: ")
n7 = input("digite o 7º numero: ")
n8 = input("digite o 8º numero: ")
n9 = input("digite o 9º numero: ")
n10 = input("digite o 10º numero: ")

lista = [n1, n2, n3, n4, n5, n6, n7, n8, n9, n10]
print("lista normal")
print(lista)
lista.sort()
print("lista em ordem")
print(lista)
lista_sem_repiti = list(set(lista))
print("lista sem repetição")
print(lista_sem_repiti)